version: 2

jobs:
  macos:
    macos:
      xcode: "9.3"
    steps:
      - checkout
      - run: 
          name: Compile code
          command: swift build
      - run: 
          name: Run unit tests
          command: swift test
  macos-release:
    macos:
      xcode: "9.3"
    steps:
      - checkout
      - run: 
          name: Compile code with optimizations
          command: swift build -c release
  linux:
    docker:
      - image: swift:4.1
    steps:
      - checkout
      - run: 
          name: Compile code
          command: swift build
      - run: 
          name: Run unit tests
          command: swift test
  linux-release:
    docker:
      - image: swift:4.1
    steps:
      - checkout
      - run: 
          name: Compile code with optimizations
          command: swift build -c release

workflows:
  version: 2
  tests:
    jobs:
      - linux
      - linux-release
      - macos
      - macos-release

  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - linux